### ISSUE TITLE
[RAMeka] Using a custom theme makes the emulator unable to boot

### ISSUE THREAD

**Issue by Blazekickn** [RetroAchievements/RAEmus#79]
Changing the theme makes the emulator unable to start up on future sessions. Editing the default "Ocean" theme does the same thing.

**Comment by Blazekickn** [comment]
After further testing the only options that don't work when changed are background color and background grid color, and only if they don't match.

**Comment by Jamiras** [comment]
Looks like it was fixed by this: https://github.com/ocornut/meka/pull/44. We're just out of date.

I can't find an exact commit that we line up with - we do have https://github.com/ocornut/meka/commit/f82b72bfa9420eafd0bc0f013803e6680fd66bda (12/1/18), but don't have https://github.com/ocornut/meka/commit/5ad92c2893c3d34cfea5393daf46d3be56ced2ce (12/27/18), so apparently we have some older commit with a few additional changes.

**Comment by Jamiras** [comment]
Fix is included in RAMeka 1.0
